weather_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DWH_HOST', 'localhost') }}"
      port: "{{ env_var('DWH_PORT', '5432') | int }}"
      user: "{{ env_var('DWH_USER', 'dwh') }}"
      password: "{{ env_var('DWH_PASSWORD', 'dwh') }}"
      dbname: "{{ env_var('DWH_DB', 'dwh') }}"
      schema: dbt
      threads: 4
    prod:
      type: postgres
      host: "{{ env_var('DWH_HOST') }}"
      port: "{{ env_var('DWH_PORT') | int }}"
      user: "{{ env_var('DWH_USER') }}"
      password: "{{ env_var('DWH_PASSWORD') }}"
      dbname: "{{ env_var('DWH_DB') }}"
      schema: dbt
      threads: 4
